pipeline {
    agent none
    options {
        skipStagesAfterUnstable()
    }
    stages {
        stage('Build') {
            agent {
                docker {
                    image 'python:3.11.5-alpine3.18'
                }
            }
            steps {
                sh 'python -m py_compile sources/add2vals.py sources/calc.py'
                stash(name: 'compiled-results', includes: 'sources/*.py*')
            }
        }
        stage('Test') {
            agent {
                docker {
                    image 'qnib/pytest'
                }
            }
            steps {
                sh 'py.test --junit-xml test-reports/results.xml sources/test_calc.py'
            }
            post {
                always {
                    junit 'test-reports/results.xml'
                }
            }
        }
         stage('Manual Approval') {
            input {
                message 'Proceed to Deploy?'
                ok 'Proceed'
                parameters {
                    booleanParam(
                        name: 'PROCEED_TO_DEPLOY',
                        defaultValue: false,
                        description: 'Klik Proceed untuk melanjutkan atau Abort untuk menghentikan eksekusi pipeline'
                    )
                }
            }
            steps {
                script {
                    if (params.PROCEED_TO_DEPLOY) {
                        echo 'User has chosen to proceed to Deploy stage.'
                    } else {
                        currentBuild.result = 'ABORTED'
                        error('User has chosen to abort the pipeline.')
                    }
                }
            }
        }
        stage('Deploy') { 
            agent any
            environment { 
                VOLUME = '$(pwd)/sources:/src'
                IMAGE = 'cdrx/pyinstaller-linux:python2'
            }
            steps {
                dir(path: env.BUILD_ID) { 
                    unstash(name: 'compiled-results') 
                    sh "docker run --rm -v ${VOLUME} ${IMAGE} 'pyinstaller -F add2vals.py'" 
                }
            }
            post {
                success {
                    archiveArtifacts "${env.BUILD_ID}/sources/dist/add2vals" 
                    sh "docker run --rm -v ${VOLUME} ${IMAGE} 'rm -rf build dist'"
                }
            }
        }
    }
}