node {
    stage('Build') {
        docker.image('python:2-alpine').inside {
            sh 'ls'
            sh 'python -m py_compile sources/add2vals.py sources/calc.py'
        }
    }
    stage('Test') {
        docker.image('qnib/pytest').inside {
            sh 'py.test --verbose --junit-xml test-reports/results.xml sources/test_calc.py'
        }
    }
    stage('Deploy') {
        docker.image('cdrx/pyinstaller-linux:python2').inside {
            echo 'Delivering...'
            sh 'pyinstaller --onefile sources/add2vals.py'
        }
        post {
            success {
                echo 'Post success...'
                archiveArtifacts artifacts: 'dist/add2vals', allowEmptyArchive: true
            }
        }
    }
}
